name: crystal_property_predictor

channels:
  - conda-forge
  - pytorch

dependencies:
  - absl-py
  - black
  - click
  - cudatoolkit=10.0
  - flake8
  - numpy
  - pandas
  - pip
  - pytest
  - python=3.11
  - pytorch>=1.1.0
  - pyyaml
  - rope
  - scipy
  - tensorboard>=1.14
  - torchvision
  - pip:
      - -e .  # install package in development mode
