name: crystal_property_predictor

channels:
  - conda-forge
  - pytorch

dependencies:
  - absl-py
  - black
  - click
  - cudatoolkit=10.0
  - flake8
  - isort
  - mypy
  - numpy
  - overrides
  - packaging
  - pandas
  - pip
  - pydocstyle
  - pyproject-flake8
  - pytest
  - python=3.11
  - pytorch>=1.1.0
  - pyyaml
  - scikit-learn
  - scipy
  - tensorboard
  - torchvision
  - types-pyyaml
  - pip:
      - torcheval
      - -e .  # install package in development mode
