name: crystal_property_predictor

channels:
  - nvidia
  - pytorch
  - conda-forge

dependencies:
  - absl-py
  - black
  - click
  - flake8
  - isort
  - mypy
  - numpy
  - overrides
  - packaging
  - pandas
  - pip
  - pydocstyle
  - pyproject-flake8
  - pytest
  - python=3.11
  - pytorch-cuda=12.1
  - pyyaml
  - scikit-learn
  - scipy
  - tensorboard
  - torchvision
  - types-pyyaml
  - pip:
      - torcheval
      - -e .  # install package in development mode
