name: crystal_property_predictor

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - pytest
  - flake8
  - rope
  - black
  - click
  - pyyaml
  - pytorch>=1.1.0
  - torchvision
  - cudatoolkit=10.0
  - tensorboard>=1.14
  - absl-py
  - pip
  - pip:
      - -e .  # install package in development mode
